{
	"name": "CVE-2019-16729",
	"seq": "2019-16729",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20190924"
	},
	"desc": "pam-python before 1.0.7-1 has an issue in regard to the default environment variable handling of Python, which could allow for local root escalation in certain PAM setups.",
	"refs": [
		{
			"text": "DSA-4555",
			"source": "DEBIAN",
			"url": "https://www.debian.org/security/2019/dsa-4555"
		},
		{
			"text": "https://bugzilla.suse.com/show_bug.cgi?id=1150510#c1",
			"source": "MISC",
			"url": "https://bugzilla.suse.com/show_bug.cgi?id=1150510#c1"
		},
		{
			"text": "https://sourceforge.net/p/pam-python/code/ci/0247ab687b4347cc52859ca461fb0126dd7e2ebe/",
			"source": "MISC",
			"url": "https://sourceforge.net/p/pam-python/code/ci/0247ab687b4347cc52859ca461fb0126dd7e2ebe/"
		},
		{
			"text": "https://tracker.debian.org/news/1066790/accepted-pam-python-107-1-source-amd64-all-into-unstable/",
			"source": "MISC",
			"url": "https://tracker.debian.org/news/1066790/accepted-pam-python-107-1-source-amd64-all-into-unstable/"
		},
		{
			"text": "[debian-lts-announce] 20191123 [SECURITY] [DLA 2000-1] pam-python security update",
			"source": "MLIST",
			"url": "https://lists.debian.org/debian-lts-announce/2019/11/msg00020.html"
		},
		{
			"text": "USN-4552-1",
			"source": "UBUNTU",
			"url": "https://usn.ubuntu.com/4552-1/"
		},
		{
			"text": "USN-4552-2",
			"source": "UBUNTU",
			"url": "https://usn.ubuntu.com/4552-2/"
		}
	],
	"votes": {}
}
