{
	"name": "CVE-2019-20426",
	"seq": "2019-20426",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20200127"
	},
	"desc": "In the Lustre file system before 2.12.3, the ptlrpc module has an out-of-bounds access and panic due to the lack of validation for specific fields of packets sent by a client. In the function ldlm_cancel_hpreq_check, there is no lock_count bounds check.",
	"refs": [
		{
			"text": "http://lustre.org/",
			"source": "MISC",
			"url": "http://lustre.org/"
		},
		{
			"text": "http://wiki.lustre.org/Lustre_2.12.3_Changelog",
			"source": "MISC",
			"url": "http://wiki.lustre.org/Lustre_2.12.3_Changelog"
		},
		{
			"text": "https://jira.whamcloud.com/browse/LU-12614",
			"source": "MISC",
			"url": "https://jira.whamcloud.com/browse/LU-12614"
		},
		{
			"text": "https://review.whamcloud.com/#/c/36107/",
			"source": "MISC",
			"url": "https://review.whamcloud.com/#/c/36107/"
		}
	],
	"votes": {}
}
