{
	"name": "CVE-2022-0718",
	"seq": "2022-0718",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20220222"
	},
	"desc": "A flaw was found in python-oslo-utils. Due to improper parsing, passwords with a double quote ( \" ) in them cause incorrect masking in debug logs, causing any part of the password after the double quote to be plaintext.",
	"refs": [
		{
			"text": "https://lists.debian.org/debian-lts-announce/2022/09/msg00015.html",
			"source": "MISC",
			"url": "https://lists.debian.org/debian-lts-announce/2022/09/msg00015.html"
		},
		{
			"text": "https://access.redhat.com/security/cve/CVE-2022-0718",
			"source": "MISC",
			"url": "https://access.redhat.com/security/cve/CVE-2022-0718"
		},
		{
			"text": "https://bugs.launchpad.net/oslo.utils/+bug/1949623",
			"source": "MISC",
			"url": "https://bugs.launchpad.net/oslo.utils/+bug/1949623"
		},
		{
			"text": "https://bugzilla.redhat.com/show_bug.cgi?id=2056850",
			"source": "MISC",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2056850"
		},
		{
			"text": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa",
			"source": "MISC",
			"url": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa"
		},
		{
			"text": "https://security-tracker.debian.org/tracker/CVE-2022-0718",
			"source": "MISC",
			"url": "https://security-tracker.debian.org/tracker/CVE-2022-0718"
		}
	],
	"votes": {}
}
