{
	"name": "CVE-2021-28676",
	"seq": "2021-28676",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20210318"
	},
	"desc": "An issue was discovered in Pillow before 8.2.0. For FLI data, FliDecode did not properly check that the block advance was non-zero, potentially leading to an infinite loop on load.",
	"refs": [
		{
			"text": "FEDORA-2021-77756994ba",
			"source": "FEDORA",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/"
		},
		{
			"text": "GLSA-202107-33",
			"source": "GENTOO",
			"url": "https://security.gentoo.org/glsa/202107-33"
		},
		{
			"text": "https://github.com/python-pillow/Pillow/commit/bb6c11fb889e6c11b0ee122b828132ee763b5856",
			"source": "MISC",
			"url": "https://github.com/python-pillow/Pillow/commit/bb6c11fb889e6c11b0ee122b828132ee763b5856"
		},
		{
			"text": "https://github.com/python-pillow/Pillow/pull/5377",
			"source": "MISC",
			"url": "https://github.com/python-pillow/Pillow/pull/5377"
		},
		{
			"text": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28676-fix-fli-dos",
			"source": "MISC",
			"url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28676-fix-fli-dos"
		},
		{
			"text": "[debian-lts-announce] 20210722 [SECURITY] [DLA 2716-1] pillow security update",
			"source": "MLIST",
			"url": "https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html"
		}
	],
	"votes": {}
}
