{
	"name": "CVE-2021-4150",
	"seq": "2021-4150",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20211221"
	},
	"desc": "A use-after-free flaw was found in the add_partition in block/partitions/core.c in the Linux kernel. A local attacker with user privileges could cause a denial of service on the system. The issue results from the lack of code cleanup when device_add call fails when adding a partition to the disk.",
	"refs": [
		{
			"text": "https://bugzilla.redhat.com/show_bug.cgi?id=2025938",
			"source": "MISC",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2025938"
		},
		{
			"text": "https://lkml.org/lkml/2021/10/18/485",
			"source": "MISC",
			"url": "https://lkml.org/lkml/2021/10/18/485"
		},
		{
			"text": "https://lkml.org/lkml/2021/9/6/781",
			"source": "MISC",
			"url": "https://lkml.org/lkml/2021/9/6/781"
		}
	],
	"votes": {}
}
